# Generated by Django 5.1.7 on 2025-03-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_team_name_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tournament.game'),
            preserve_default=False,
        ),
    ]
