# Generated by Django 5.1.7 on 2025-03-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_team_user_team_name_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
