# Generated by Django 5.1.7 on 2025-03-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_game_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
